#所有服务通用的配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  hystrix:
    enabled: true
    
eureka:
  client:
    healthcheck:
      enabled: true
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 16000
ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 2000
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false
    
spring:
  redis:
    database: 0
    host: 10.1.94.61
    port: 6379
    timeout: 1000
  data:
     mongodb:
       uri: mongodb://10.1.94.61:27017/attendance
       field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
  datasource:
     url: jdbc:mysql://10.1.94.61:3306/${db.name}
     username: root
     password: labor
     driver-class-name: com.mysql.jdbc.Driver

producer-rocker-mq-config:
  mq: rocketMq
  nameSrvAddress: 192.168.133.239:9876
  producerGroup: glm

consumer-rocker-mq-config:
  mq: rocketMq
  nameSrvAddress: 192.168.133.239:9876
  producerGroup: glm
