spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: glodon
    timeout: 20000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0